services:

  # 0. MongoDB
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - task-network
    restart: unless-stopped

  # 1. API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: ./backend/apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - '3000:3000'
    environment:
      - AUTH_HOST=auth-service
      - AUTH_PORT=3001
      - PROJECT_HOST=project-service
      - PROJECT_PORT=3002
      - TASK_HOST=task-service
      - TASK_PORT=3003
      - PORT=3000
      - FRONTEND_URL=http://80.225.204.112/task-manager
    depends_on:
      - mongodb
      - auth-service
      - project-service
      - task-service
    networks:
      - task-network

  # 2. Auth Service
  auth-service:
    build:
      context: .
      dockerfile: ./backend/apps/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - '3001:3001'
    environment:
      # Connect to MongoDB container (same network)
      - MONGO_URI=mongodb://mongodb:27017/task-manager
      - JWT_SECRET=super_secret_key_for_assessment
      - AUTH_HOST=0.0.0.0
      - AUTH_PORT=3001
    networks:
      - task-network

  # 3. Project Service
  project-service:
    build:
      context: .
      dockerfile: ./backend/apps/project-service/Dockerfile
    container_name: project-service
    ports:
      - '3002:3002'
    environment:
      # Connect to MongoDB container (same network)
      - MONGO_URI=mongodb://mongodb:27017/task-manager
      - PROJECT_HOST=0.0.0.0
      - PROJECT_PORT=3002
    networks:
      - task-network

  # 4. Task Service
  task-service:
    build:
      context: .
      dockerfile: ./backend/apps/task-service/Dockerfile
    container_name: task-service
    ports:
      - '3003:3003'
    environment:
      # Connect to MongoDB container (same network)
      - MONGO_URI=mongodb://mongodb:27017/task-manager
      - TASK_HOST=0.0.0.0
      - TASK_PORT=3003
      # Connect to Project Service (for task validation)
      - PROJECT_HOST=project-service
      - PROJECT_PORT=3002
    depends_on:
      - project-service
    networks:
      - task-network

  # 5. Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://80.225.204.112/task-manager/api
    container_name: task-manager-frontend
    ports:
      - '5173:5173'
    depends_on:
      - api-gateway
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  mongodb_data: