version: '3.8'

services:

  # 1. API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: ./backend/apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - '3000:3000'
    environment:
      - AUTH_HOST=auth-service
      - AUTH_PORT=3001
      - PROJECT_HOST=project-service
      - PROJECT_PORT=3002
      - TASK_HOST=task-service
      - TASK_PORT=3003
      - PORT=3000
    depends_on:
      - auth-service
      - project-service
      - task-service
    networks:
      - task-network

  # 2. Auth Service
  auth-service:
    build:
      context: .
      dockerfile: ./backend/apps/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - '3001:3001'
    environment:
      # Connect to MongoDB on the host machine (VPS)
      - MONGO_URI=mongodb://host.docker.internal:27017/task-manager
      - JWT_SECRET=super_secret_key_for_assessment
      - AUTH_HOST=localhost
      - AUTH_PORT=3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - task-network

  # 3. Project Service
  project-service:
    build:
      context: .
      dockerfile: ./backend/apps/project-service/Dockerfile
    container_name: project-service
    ports:
      - '3002:3002'
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/task-manager
      - PROJECT_HOST=localhost
      - PROJECT_PORT=3002
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - task-network

  # 4. Task Service
  task-service:
    build:
      context: .
      dockerfile: ./backend/apps/task-service/Dockerfile
    container_name: task-service
    ports:
      - '3003:3003'
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/task-manager
      - TASK_HOST=localhost
      - TASK_PORT=3003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - project-service
    networks:
      - task-network

  # 5. Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-manager-frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api-gateway
    networks:
      - task-network

networks:
  task-network:
    driver: bridge